version: '3.8'
services:
  app:
    image: antunesgabriel/fullcycle-node
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: antunes
      DB_PASSWORD: antunes
      DB_DATABASE: challenge
    networks:
      - application
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: antunes
      MYSQL_PASSWORD: antunes
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./volumes/mysql:/var/lib/mysqlb"
    networks:
      - application
  webservice:
    image: nginx:1.25.2-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app
    networks:
      - application
networks:
  application:
    driver: bridge
